name: Build Docker Images

on: push

env:
  QBS_BRANCH: v1.18.0
  QT_MAJOR: "515"
  QT_VERSION: "5.15.2"

jobs:
  qbs-clang:
    name: "Qbs + Clang"
    strategy:
      fail-fast: false
      matrix:
        include:
          - clang_major: 8
            distro: xenial
          - clang_major: 9
            distro: focal
          - clang_major: 10
            distro: focal
          - clang_major: 11
            distro: focal
          - clang_major: 12
            distro: focal
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Clang${{ matrix.clang_major }} + Qbs ${{ env.QBS_BRANCH }}
        uses: docker/build-push-action@v1
        with:
          target: qbs-clang
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          repository: arbmind/qbs-clang${{ matrix.clang_major }}
          tags: latest,qbs_${{ env.QBS_BRANCH }}
          build_args: DISTRO=${{ matrix.distro }},CLANG_MAJOR=${{ matrix.clang_major }},QT_MAJOR=${{ env.QT_MAJOR }},QT_VERSION=${{ env.QT_VERSION }},QBS_BRANCH=${{ env.QBS_BRANCH }}

      - name: Clang${{ matrix.clang_major }} + Qt ${{ env.QT_VERSION }} + Qbs ${{ env.QBS_BRANCH }}
        uses: docker/build-push-action@v1
        with:
          target: qbs-clang-qt
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          repository: arbmind/qbs-clang${{ matrix.clang_major }}-qt${{ env.QT_MAJOR }}
          tags: latest,qbs_${{ env.QBS_BRANCH }}
          build_args: DISTRO=${{ matrix.distro }},CLANG_MAJOR=${{ matrix.clang_major }},QT_MAJOR=${{ env.QT_MAJOR }},QT_VERSION=${{ env.QT_VERSION }},QBS_BRANCH=${{ env.QBS_BRANCH }}
