name: Build Docker Images

on: push

env:
  QBS_BRANCH: v1.21.0
  QT_MAJOR: "62"
  QT_VERSION: "6.2.4"
  DOCKER_FILE: "Dockerfile.qt6"

jobs:
  qbs-clang:
    name: "Qbs + Clang"
    strategy:
      fail-fast: false
      matrix:
        include:
          - clang_major: 11
            distro: focal
          - clang_major: 12
            distro: focal
          - clang_major: 13
            distro: focal
          - clang_major: 14
            distro: focal
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Clang${{ matrix.clang_major }} + Qbs ${{ env.QBS_BRANCH }}
        uses: docker/build-push-action@v2
        with:
          target: qbs-clang
          push: ${{ github.event_name != 'pull_request' }}
          file: ${{ env.DOCKER_FILE }}
          tags: |
            arbmind/qbs-clang${{ matrix.clang_major }}:latest
            arbmind/qbs-clang${{ matrix.clang_major }}:qbs_${{ env.QBS_BRANCH }}
          build-args: |
            DISTRO=${{ matrix.distro }}
            CLANG_MAJOR=${{ matrix.clang_major }}
            QT_MAJOR=${{ env.QT_MAJOR }}
            QT_VERSION=${{ env.QT_VERSION }}
            QBS_BRANCH=${{ env.QBS_BRANCH }}

      - name: Clang${{ matrix.clang_major }} + Qt ${{ env.QT_VERSION }} + Qbs ${{ env.QBS_BRANCH }}
        uses: docker/build-push-action@v2
        with:
          target: qbs-clang-qt
          push: ${{ github.event_name != 'pull_request' }}
          file: ${{ env.DOCKER_FILE }}
          tags: |
            arbmind/qbs-clang${{ matrix.clang_major }}-qt${{ env.QT_MAJOR }}:latest
            arbmind/qbs-clang${{ matrix.clang_major }}-qt${{ env.QT_MAJOR }}:qbs_${{ env.QBS_BRANCH }}
          build-args: |
            DISTRO=${{ matrix.distro }}
            CLANG_MAJOR=${{ matrix.clang_major }}
            QT_MAJOR=${{ env.QT_MAJOR }}
            QT_VERSION=${{ env.QT_VERSION }}
            QBS_BRANCH=${{ env.QBS_BRANCH }}
